In [29]:
import cv2
import mediapipe as mp
import numpy as np
import time 
import pyrealsense2 as rs
import math as m
import matplotlib.pyplot as plt
from PIL import Image
import time
import os
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torch.utils.data.sampler import SubsetRandomSampler
import torch.nn.functional as F

In [30]:
def convert_landmark_to_array(landmarks):
    landmarks_array = np.array(
        [[landmark.x, landmark.y, landmark.z] for landmark in landmarks])
    return landmarks_array

## Load the trained model

In [31]:
class ConvNet(nn.Module):
    def __init__(self, n_input_channels=3, n_output=4):
        super().__init__()
    
        # input = 75x20x3
        self.conv1 = nn.Conv2d(n_input_channels, 32, kernel_size=3, padding=1)
        self.bn1 = nn.BatchNorm2d(32)
        
        # input = 37x10x32
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, padding=1)
        self.bn2 = nn.BatchNorm2d(64)
        
        # input = 18x5x64
        self.conv3 = nn.Conv2d(64, 128, kernel_size=3, padding=1)
        self.bn3 = nn.BatchNorm2d(128)
        
        # input = 9x2x128
        self.fc1 = nn.Linear(128*9*2, 1024)
        self.fc2 = nn.Linear(1024, n_output)

    
    def forward(self, x):
        
        x = F.relu(self.bn1(self.conv1(x)))
        x = F.max_pool2d(x, 2) #maxpool of kernel size 2 to reduce the size of the images by a factor 2
        x = F.relu(self.bn2(self.conv2(x)))
        x = F.max_pool2d(x, 2)
        x = F.relu(self.bn3(self.conv3(x)))
        x = F.max_pool2d(x, 2)
        x = x.view(-1, 128*9*2) #flatten
        x = F.relu(self.fc1(x))
        x = self.fc2(x)

        return x
    
    def predict(self, x):
        logits = self.forward(x)
        return F.softmax(logits)

In [32]:
torch.cuda.is_available()

True

In [33]:
CHECKPOINT = "trained_model.pth"
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)
model = ConvNet().to(device)
model.load_state_dict(torch.load(CHECKPOINT))
model.eval()

# useful for normalization
dataset_mean = np.load("dataset_mean.npy")
dataset_std = np.load("dataset_std.npy")

cuda


In [34]:
dataset_mean

array([ 0.51007978,  0.59016526, -0.06745971])

In [35]:
def normalize_data(data):
    new_data = np.zeros(data.shape)
    new_data[:,:,0] = (data[:,:,0] - dataset_mean[0])/dataset_std[0]
    new_data[:,:,1] = (data[:,:,1] - dataset_mean[1])/dataset_std[1]
    new_data[:,:,2] = (data[:,:,2] - dataset_mean[2])/dataset_std[2]
    return new_data


In [36]:
label_dict = {"come":0,"lie down":1,"sit":2,"stay":3}
inv_label_dict = {v: k for k, v in label_dict.items()}

In [27]:
new_frame_time = 0
prev_frame_time = 0

predicted_class_name = "hee"


# could find a way of finding this value automatically
frames_by_sec = 20 - 1
n_frames = 0
landmark_image = np.empty((75,3))

#hollistic detects posiiton, face and hand landmarks
mp_holistic = mp.solutions.holistic
holistic_model = mp_holistic.Holistic(
    model_complexity=1,
    min_detection_confidence=0.5,
    min_tracking_confidence=0.5
)

mp_drawing = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles

moves = ["sit", "lie down", "stay", "come"]


n_samples = 30 # number of times we will record each move
current_sample = 0 # current sample we are recording
current_move = 0

cap = cv2.VideoCapture(0)
cv2.namedWindow("image", cv2.WINDOW_NORMAL)
while cap.isOpened():
    success, image = cap.read()
    if not success:
      print("Ignoring empty camera frame.")
      # If loading a video, use 'break' instead of 'continue'.
      continue

    n_frames += 1

    if n_frames > 20:
      if n_frames % 20 == 0:
        # convert to tensor
        data = landmark_image[:,:,-20:]
        data = np.transpose(data, (0, 2, 1))
        data = np.transpose(data, (2, 0, 1))
        data = np.nan_to_num(data)
        data = np.clip(data, -10, 10)
        # print("before normalization")
        # print(data)
        data = normalize_data(data)
        # print("after normalization")
        # print(data)
        data = torch.tensor(data).float() 
        # print(data.shape)
        # data = data.transpose(1,0,2)
        data = torch.unsqueeze(data, 0)
        # print(data.shape)
        data = data.to(device)

        # predict
        output = model.predict(data)
        print(f"frame {n_frames}")
        print(output)
        # get the predicted class
        if torch.max(output) > 0.8:
          predicted_class = torch.argmax(output, dim=1)
          predicted_class_name = inv_label_dict[int(predicted_class)]

    # compute fps
    new_frame_time = time.time()
    fps = 1/(new_frame_time-prev_frame_time)
    prev_frame_time = new_frame_time

    # compute keypoints etc...
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
    image.flags.writeable = False
    results = holistic_model.process(image)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    # convert landmarks to array with exception handling (zero array if not detected)
    try:
      pose_landmarks = convert_landmark_to_array(results.pose_landmarks.landmark)
    except:
      #  print("no pose landmarks detected")
       pose_landmarks = np.zeros((33,3))
    try:
      left_hand_landmarks = convert_landmark_to_array(results.left_hand_landmarks.landmark)
    except:
      # print("no left hand landmarks detected")
      left_hand_landmarks = np.zeros((21,3))
    try:
      right_hand_landmarks = convert_landmark_to_array(results.right_hand_landmarks.landmark)
    except:
      # print("no right hand landmarks detected")
      right_hand_landmarks = np.zeros((21,3))

    hands_and_pose_array = np.concatenate((pose_landmarks, left_hand_landmarks, right_hand_landmarks), axis=0)
    landmark_image = np.dstack((landmark_image, hands_and_pose_array))

    # Drawing the annotiations
    image.flags.writeable = True
    
    # Drawing Pose Landmarks
    mp_drawing.draw_landmarks(
        image,
        results.pose_landmarks,
        mp_holistic.POSE_CONNECTIONS,
        landmark_drawing_spec=mp_drawing_styles.get_default_pose_landmarks_style())
    
    # Drawing Right hand Landmarks
    mp_drawing.draw_landmarks(
      image,
      results.right_hand_landmarks,
      mp_holistic.HAND_CONNECTIONS
    )
 
    # Drawing Left hand Landmarks
    mp_drawing.draw_landmarks(
      image,
      results.left_hand_landmarks,
      mp_holistic.HAND_CONNECTIONS
    )

    fps = str(int(fps))
    image = cv2.flip(image,1)
    cv2.putText(image, fps, (7, 70), 1, 3, (100, 255, 0), 3, cv2.LINE_AA)
    cv2.putText(image, predicted_class_name, (7, 100), 1, 3, (100, 255, 0), 3, cv2.LINE_AA)
    cv2.imshow('image', image)
    c = cv2.waitKey(1)
    if c == 27: # press escape to quit
        break
cap.release()
cv2.destroyAllWindows()

/tmp/ipykernel_10633/3701468882.py:38: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return F.softmax(logits)


frame 40
tensor([[5.7739e-04, 3.8005e-01, 6.8228e-04, 6.1869e-01]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)
frame 60
tensor([[0.0008, 0.4347, 0.0008, 0.5637]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)
frame 80
tensor([[0.0007, 0.4609, 0.0009, 0.5375]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)
frame 100
tensor([[0.0007, 0.4465, 0.0009, 0.5520]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)
frame 120
tensor([[1.0234e-03, 2.0104e-01, 2.5327e-04, 7.9769e-01]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)
frame 140
tensor([[6.3297e-04, 5.5168e-02, 3.6349e-04, 9.4384e-01]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)
frame 160
tensor([[2.2451e-04, 1.2395e-01, 1.6380e-04, 8.7566e-01]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)
frame 180
tensor([[2.6847e-04, 1.4368e-01, 1.0319e-04, 8.5595e-01]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)
frame 200
tensor([[4.4016e-03, 2.9548e-01, 2.8680e-04, 6.9983e-01]], device='cuda:0

In [28]:
print(landmark_image[:,:,40:60])

[[[ 0.57543206  0.57580936  0.57713217 ...  0.55239332  0.55198002
    0.55117744]
  [ 0.41942284  0.42004308  0.41875026 ...  0.40985876  0.41184559
    0.41329852]
  [-1.30985749 -1.29141164 -1.29826665 ... -1.35136628 -1.53660369
   -1.53420484]]

 [[ 0.60451788  0.60545415  0.60664648 ...  0.59008121  0.58919567
    0.58810782]
  [ 0.35109404  0.35150319  0.34848031 ...  0.34219816  0.34510046
    0.3467674 ]
  [-1.2514509  -1.23845208 -1.24429297 ... -1.29650843 -1.48042607
   -1.47882533]]

 [[ 0.61746204  0.61828625  0.61942834 ...  0.60547167  0.60470277
    0.60366195]
  [ 0.35463998  0.35508117  0.35389078 ...  0.34539926  0.34830007
    0.34978008]
  [-1.25121236 -1.23813081 -1.24394679 ... -1.29606998 -1.47994792
   -1.47841942]]

 ...

 [[ 0.          0.          0.         ...  0.          0.
    0.        ]
  [ 0.          0.          0.         ...  0.          0.
    0.        ]
  [ 0.          0.          0.         ...  0.          0.
    0.        ]]

 [[ 0.        

In [16]:

torch.set_printoptions(threshold=10_000)

In [17]:
cap.release()
cv2.destroyAllWindows()